[package]
name    = "heraldcore"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chainmail     = { git = "https://github.com/kalix-systems/chainmail" }
chrono        = { version = "0.4.7", default_features  = false}
herald_common = { path    = "../herald_common", default_features = false, features = ["rusqlite_"] }
image         = { version = "0.22.1", default_features = false, features = ["jpeg", "png_codec"]}
lazy_pond     = { path    = "../lazy_pond" }
lazy_static   = "1.3.0"
libsodium-sys = "0.2.4"
regex         = "1.2.1"
rusqlite      = { version = "0.20.0", default_features = false, features = ["functions"]}
serde         = "1.0.99"
serde_bytes   = "0.11.2"
serde_cbor    = "0.10.1"
sodiumoxide   = "0.2.4"
ureq          = { version = "0.11", default_features = false }
url           = "2.1"
websocket     = { version = "0.23", default_features = false, features = ["sync"] }
tar = "0.4.26"
hex = "0.4.0"

[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"
