[package]
name    = "heraldcore"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>", "mobile-bungalow <pwmay@ucsc.edu>", "theseriousadult <jack@kalix.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.3.9"
hex               = "0.4.0"
lazy_static       = "1.3.0"
libsodium-sys     = "0.2.4"
regex             = "1.2.1"
serde             = "1.0.99"
serde_bytes       = "0.11.2"
serde_cbor        = "0.10.1"
sodiumoxide       = "0.2.4"
tar               = "0.4.26"
url               = "2.1"
parking_lot = "0.9.0"

[dependencies.herald_common]
path             = "../herald_common"
default_features = false
features         = ["rusqlite_"]

[dependencies.lazy_pond]
path = "../lazy_pond"

[dependencies.chainmail]
git = "https://github.com/kalix-systems/chainmail"

[dependencies.websocket]
version          = "0.23"
default_features = false
features         = ["sync"]

[dependencies.ureq]
version          = "0.11"
default_features = false

[dependencies.rusqlite]
version          = "0.20.0"
default_features = false
features         = ["functions"]

[dependencies.image]
version          = "0.22.1"
default_features = false
features         = ["jpeg", "png_codec"]

[dependencies.pulldown-cmark]
version  = "0.6.0"
# optional = true

#[features]
#markdown = ["pulldown-cmark"]

[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"
