[package]
name    = "heraldcore"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>", "mobile-bungalow <pwmay@ucsc.edu>", "theseriousadult <jack@kalix.io>", "Kaavya Jayram <kaavya.nj@gmail.com>"]
edition = "2018"

[dependencies]
backtrace = "0.3.40"
crossbeam-channel = "0.3.9"
hex               = "0.4.0"
lazy_static       = "1.3.0"
libsodium-sys     = "0.2.4"
parking_lot       = "0.9.0"
serde             = "1.0.99"
serde_bytes       = "0.11.2"
tar               = "0.4.26"
url               = "2.1"

[dependencies.herald_common]
path             = "../herald_common"
default_features = false
features         = ["rusqlite_"]

[dependencies.kcl]
path = "../kcl"

[dependencies.kdf_ratchet]
path = "../kdf_ratchet"

[dependencies.coretypes]
path = "./coretypes"

[dependencies.coremacros]
path = "./coremacros"

[dependencies.coreconf]
path = "./coreconf"

[dependencies.network_types]
path = "./network_types"

[dependencies.location]
path = "./location"

[dependencies.search_pattern]
path = "./search_pattern"

[dependencies.platform_dirs]
path = "./platform_dirs"

[dependencies.chainkeys]
path = "./chainkeys"


[dependencies.websocket]
version          = "0.23"
default_features = false
features         = ["sync"]

[dependencies.ureq]
version          = "0.11"
default_features = false

[dependencies.rusqlite]
version          = "0.20.0"
default_features = false
features         = ["bundled"]

[dependencies.image]
version          = "0.22.1"
default_features = false
features         = ["jpeg", "png_codec"]

[features]
deploy_desktop = ["platform_dirs/deploy_desktop"]


[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"
