[package]
name = "kson_derive"
version = "0.1.0"
authors = [ 
  "theseriousadult <jack@gallabytes.com>",
  "Baeo Maltinksy <baeo.maltinsky@gmail.com>"
]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
