[workspace]

members = [
  "chainmail",
  "channel_ratchet",
  "herald_common",
  "herald_server",
  "herald_server/server_store",
  "herald_server/server_errors",
  "heraldcore",
  "libherald",
  "libherald/qt_bindgen",
  "kcl",
  "kson",
  "kson/kson_derive"
]
