[workspace]

members = [
  "herald_common",
  "herald_server",
  "herald_server/server_store",
  "herald_server/server_errors",
  "herald_server/server_protocol",
  "heraldcore",
  "heraldcore/coretypes",
  "heraldcore/coremacros",
  "heraldcore/coreconf",
  "heraldcore/network_types",
  "heraldcore/chainkeys",
  "heraldcore/platform_dirs",
  "heraldcore/search_pattern",
  "heraldcore/location",
  "kcl",
  "kdf_ratchet",
  "kson",
  "kson/kson_derive",
  "libherald",
  "libherald/messages_helper",
  "libherald/qt_bindgen",
]
