[env]
LINUX_DEPLOY_DL = "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
QT_PLUGIN_DL = "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
OUT_DIR = ".appimage"

# Builds libherald with desktop deployment feature
[tasks.build_libherald]
private = true
script = [
    '''
    cd libherald
    cargo build --release --features deploy
    '''
]

# Creates AppImage build directory if it does not already exist
[tasks.make_out_dir]
private = true
command = "mkdir"
args = ["-p", "${OUT_DIR}"]

[tasks.make_out_dir.mac]
private = true
command = "mkdir"
args = ["-p", "build"]


# Installs the `linuxdeploy` tool, and plugins
[tasks.install_linuxdeploy]
private = true
install_script = [
  '''
  if ! [ -f "$OUT_DIR/linuxdeploy-x86_64.AppImage" ]; then
    wget "$LINUX_DEPLOY_DL" -O $OUT_DIR/linuxdeploy-x86_64.AppImage
    wget "$QT_PLUGIN_DL" -O $OUT_DIR/linuxdeploy-plugin-qt-x86_64.AppImage
    chmod +x $OUT_DIR/linuxdeploy*.AppImage
  fi
  '''
]
dependencies = ["make_out_dir"]


[tasks.check_qmake_installation]
private = true
script = [
  '''
  if ! [ -x "$(command -v qmake)" ]; then
    echo "Error: qmake is not installed." >&2
    exit 1
  fi
  '''
]

[tasks.check_macdeployqt_installation]
script = [
  '''
  if ! [ -x "$(command -v macdeployqt)" ]; then
    echo "Error: qmake is not installed." >&2
    exit 1
  fi
  if ! qmake -v | grep "[5-9].1[4-9]"; then 
    echo "Error: macdeployqt version in the PATH is too low, run Brew update or the qt maintenance tool to get a the correct version" >&2
    exit 1
  fi
  '''
]

# Runs qmake
[tasks.run_qmake]
private = true
command = "qmake"
args = ["client/desktop/herald.pro",
	"-spec", "linux-g++",
	"CONFIG+=qtquickcompiler",
	"-o", "${OUT_DIR}/Makefile"]
dependencies = ["check_qmake_installation", "make_out_dir"]

# Runs qmake macos
[tasks.run_qmake.mac]
private = true
command = "qmake"
args = ["client/desktop/herald.pro",
	"CONFIG+=qtquickcompiler",
	"-o", "build/Makefile"]
dependencies = ["check_qmake_installation","check_macdeployqt_installation", "make_out_dir"]

[tasks.setup_outdir]
workspace = false
dependencies = ["build_libherald", "run_qmake"]


[tasks.run_make]
script = [
  '''
  make -C $OUT_DIR -j$(nproc)
  '''
]
dependencies = ["setup_outdir"]

[tasks.run_make.mac]
script = [
  '''
 make -C build
  '''
]
dependencies = ["setup_outdir"]



[tasks.run_make_install]
workspace = false
command = "make"
args = ["-C", "${OUT_DIR}",
	"install", "INSTALL_ROOT=AppDir"]
dependencies = ["run_make"]


[tasks.run_make_install.mac]
workspace = false
command = "make"
args = ["-C", "build"]
dependencies = ["run_make"]

[tasks.build_appimage]
workspace = false
script = [
  '''
  export QML_SOURCES_PATHS=../client/desktop

  cd $OUT_DIR
  ./linuxdeploy-x86_64.AppImage \
    --appdir AppDir \
    --output appimage \
    --plugin qt \
    -i ../client/foundation/icons/herald.png \
    -d ../client/desktop/herald.desktop \
  '''
]
dependencies = ["run_make_install"]

[tasks.build_appbundle]
workspace = false
script = [
'''
   export QML_SOURCES_PATHS=../client/desktop
 
   cd build

   macdeployqt \
     herald.app \
    -qmldir=../client/desktop 
 
'''
]
dependencies = ["run_make_install"]

