[package]
name = "qt_bindgen"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"
license = "GPLv2"

[dependencies.riqtshaw]
git = "https://github.com/kalix-systems/rust-qt-binding-generator"
rev = "5199e4b2fc26ab361a7d37acdc8bf8cddbd25d2a"
