[package]
name = "qt_bindgen"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"
license = "GPLv2"

[dependencies.riqtshaw]
git = "https://github.com/kalix-systems/riqtshaw"
rev = "a025cfde46c86ed9395b35f959d4be839d288f4f"
