[package]
name = "qt_bindgen"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"
license = "GPLv2"

[dependencies.rust_qt_binding_generator]
# path = "../../../rqbg"
git = "https://github.com/kalix-systems/rust-qt-binding-generator"
rev = "a9316180f08c771691b0adf46d2f52bbf2eccaf0"
