[package]
name = "qt_bindgen"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"
license = "GPLv2"

[dependencies.riqtshaw]
#path = "../../../riqtshaw"
git = "https://github.com/kalix-systems/riqtshaw"
rev = "841a8dfaadab68bf3ec09cd32c504b3365315da7"
