[package]
name = "krpc"
version = "0.1.0"
authors = ["theseriousadult <jack@kalix.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes = "0.5"
futures = "0.3"
thiserror = "1.0"
quinn = "0.5"
quinn-proto = "0.5"

[dependencies.tokio]
version = "0.2"
features = ["rt-core"]

[dependencies.kson]
path = "../kson"

[dependencies.location]
path = "../location"
