[package]
name = "herald_server"
version = "0.1.0"
authors = ["theseriousadult <jack@gallabytes.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16"
untrusted = "0.7"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1"
failure = "0.1"
chrono = { version = "0.4", features = ["serde"] }
# im = {version = "13.0", features = ["serde"] }
bytes = { version = "0.4", features = ["serde"] }

