version: '3'

services:
  postgres:
    image: "postgres"
    command: postgres -c 'max_connections=10000' -c 'shared_buffers=2048MB'
    stdin_open: true
    tty: true
    volumes:
      - pg-data:/var/lib/postgresql/data
      - "/var/run/postgresql:/var/run/postgresql"

volumes:
  pg-data:

