version: '3'

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker

volumes:
  pg-data:

