[package]
name = "crypto_helpers"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"

[dependencies]
sodiumoxide       = "0.2.4"
libsodium-sys     = "0.2.4"

[dependencies.herald_common]
path             = "../../herald_common"
default_features = false
