[package]
name = "ratchet_chat"
version = "0.1.0"
authors = ["theseriousadult <jack@kalix.io>"]
edition = "2018"

[dependencies]
bytes = "0.5.3"
async-trait = "0.1.22"
double-ratchet = "0.1.0"

[dependencies.kcl]
path = "../kcl"

[dependencies.kson]
path = "../kson"
