[package]
name    = "heraldcore"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"

[dependencies]
herald_common = { path = "../../common" }
lazy_static   = "1.3"
serde_cbor    = "0.10.1"
serde         = "1.0.99"
rand          = "0.7.0"

[dependencies.rusqlite]
version          = "0.20.0"
default_features = false
features         = ["functions"]

[dependencies.chrono]
version          = "0.4.7"
default_features = false

[dependencies.regex]
version  = "1.3"
features = ["perf-cache", "perf-dfa", "perf-inline", "perf-literal"]

[dependencies.image]
version          = "0.22.1"
default_features = false
features         = ["jpeg", "png_codec"]

[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"
womp               = { git = "https://github.com/kalix-systems/womp"}
