[package]
name = "heraldcore"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite      = { version = "0.20.0", default_features = false}
chrono        = { version = "0.4.7", default_features  = false}
image         = { version = "0.22.1", default_features = false }
herald_common = { path    = "../../common" }
lazy_static   = "1.3.0"
serde_cbor    = "0.10.1"


[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"
herald_server      = {path   = "../../server/"}
