[package]
name    = "heraldcore"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite      = { version = "0.20.0", default_features = false, features = ["functions"]}
chrono        = { version = "0.4.7", default_features  = false}
herald_common = { path    = "../../common" }
tokio         = "0.2.0-alpha.4"
lazy_static   = "1.3.0"
image         = "0.22.1"
serde_cbor    = "0.10.1"
serde         = "1.0.99"
regex         = "1.2.1"
# ccl           = "5.1.5"

[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"
