[package]
name = "herald"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"
# build = "build.rs"
build = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.20.0"
libc = "0.2.60"
ffi-support = "0.3.5"

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.9.0"

[dev-dependencies]
serial_test = "0.2.0"
serial_test_derive = "0.2.0"
