[package]
name = "herald"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libc = "0.2.60"
heraldcore = {path="./heraldcore"}
herald_common = {path="../common"}
tokio         = "0.2.0-alpha.4"



[lib]
crate-type = ["cdylib", "staticlib"]

[dev-dependencies]
serial_test = "0.2.0"
serial_test_derive = "0.2.0"

[profile.release]
panic = "abort"
