[package]
name = "herald"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"


[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.9.0"
