[package]
name = "herald"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libc = "0.2.60"
heraldcore = {path="../heraldcore"}
serde_cbor    = "0.10.1"
serde         = "1.0.99"
herald_common = {path="../herald_common"}
crossbeam-channel = "0.3.9"
lazy_static = "1.4.0"
dashmap = "1.0.5"
parking_lot = "0.9.0"
notify-rust = "3.6.2"



[lib]
crate-type = ["cdylib", "staticlib"]

[dev-dependencies]
serial_test = "0.2.0"
serial_test_derive = "0.2.0"

[profile.release]
panic = "abort"
