[package]
name = "herald"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
crossbeam-channel = "0.3.9"
dashmap           = "1.0.5"
herald_common     = {path    = "../herald_common"}
heraldcore        = {path    = "../heraldcore"}
im-rc             = "13.0.0"
lazy_static       = "1.4.0"
libc              = "0.2.60"
#notify-rust       = "3.6.2"
parking_lot       = "0.9.0"
serde             = "1.0.99"
serde_cbor        = "0.10.1"



[lib]
crate-type = ["cdylib", "staticlib"]

[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"

[profile.release]
panic = "abort"
