[tasks.docs]
command = "cargo"
args = ["rustdoc", "--open", "--", "--document-private-items"]

[tasks.bindgen]
script = [
  '''
  cd qt_bindgen
  cargo run
  cd ..
  cargo fmt
  cd qt_ffi
  clang-format -i $(ls)
  '''
]
